version: 2
build:
    os: ubuntu-22.04
    tools:
        python: "mambaforge-22.9"
    jobs:
        pre_install:
            - bash ./solver/doc/scripts/pre_install.sh
sphinx:
    configuration: solver/doc/source/conf.py
conda:
    environment: solver/doc/environment.yml
