version: 2
build:
    os: "ubuntu-20.04"
    tools:
        python: "mambaforge-22.9"
    jobs:
        pre_install:
            - bash ./solver/doc/scripts/pre_install.sh
conda:
    environment: solver/doc/environment.yml
