version: 2
build:
    os: "ubuntu-20.04"
    tools:
        python: "3.10"
    conda:
        file: solver/doc/environment.yml
    jobs:
        pre_install:
            - bash ./doc/scripts/pre_install.sh
