version: 2
build:
    os: ubuntu-lts-latest
    tools:
        python: "mambaforge-latest"
    jobs:
        pre_install:
            - bash ./solver/doc/scripts/pre_install.sh
sphinx:
    configuration: solver/doc/source/conf.py
conda:
    environment: solver/doc/environment.yml
