name: ponio-test

channels:
  - conda-forge
dependencies:
  - cmake
  - ninja
  - sympy
  - numpy
  - scipy
  - matplotlib
  - notebook
  - jinja2
  - eigen
  - samurai
  - cli11
  - doctest
  - pytest
  - nbval
