name: ponio-solver-doc

channels:
  - conda-forge

dependencies:
  - cmake
  - ninja
  - graphviz
  - doxygen
  - sphinx
  - sphinx_rtd_theme
  - breathe
  - pip:
    - -r ../../analysis/requirements.txt
