name: ponio-solver-doc

channels:
  - conda-forge

dependencies:
  - sympy
  - numpy
  - jinja2
  - cmake
  - ninja
  - pkg-config
  - eigen
  - cli11
  - graphviz
  - breathe
  - doxygen
  - pydata-sphinx-theme
