name: MacOS CI

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - cpp-version: clang-14
            cc: "clang"
            cxx: "clang++"
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: solver/test/environment.yml
          environment-name: ponio-solver-test
      - name: Conda informations
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Configure
        shell: bash -l {0}
        run: |
          export LDFLAGS="${LDFLAGS} -L$CONDA_PREFIX/lib"
          cd solver
          make install
          cd test
          {{ matrix.cxx }}  --version
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} make test