name: ponio CI - [multi-os] compiler tests

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - ubuntu-22.04
          - macos-12
        CMAKE_GENERATOR:
          - "Ninja Multi-Config"
        include:
          - os: windows-2022
            compiler: msvc
            CMAKE_GENERATOR: "Visual Studio 17 2022"
        exclude:
          - os: macos-12
            compiler: llvm
          - os: windows-2022
            compiler: llvm
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.13.0
          cache: true
      - name: Install compiler
        run: pixi add cxx-compiler
      - name: Build
        run: pixi run build_test
      - name: Run tests
        run: pixi run test
