name: ponio CI - [multi-os] compiler tests

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - ubuntu-22.04
          - macos-12
        compiler:
          - llvm
          - gcc
        CMAKE_GENERATOR:
          - "Ninja Multi-Config"
        include:
          - os: windows-2022
            compiler: msvc
            CMAKE_GENERATOR: "Visual Studio 17 2022"
        exclude:
          - os: macos-12
            compiler: llvm
          - os: windows-2022
            compiler: llvm
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.13.0
          cache: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan2
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('./conanfile.py')}}-${{ matrix.CMAKE_GENERATOR }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('./conanfile.py') }}-
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
          ninja: true
          vcpkg: false
          ccache: false
          conan: 2.0.14
          clangtidy: false
          task: false
          cppcheck: false
          gcovr: false
          opencppcoverage: false
      - name: Build
        run: pixi run build_test
      - name: Run tests
        run: pixi run test
