name: ponio CI - [multi-os] compiler tests

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - ubuntu-22.04
          - macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.13.0
          cache: true
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
      - name: Install compiler and python
        run: pixi add cxx-compiler python
      - name: Build
        run: pixi run build_test
      - name: Run tests
        run: pixi run test
