name: ponio CI - [multi-os] compiler tests

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - ubuntu-22.04
          - macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.13.0
          cache: true
      - name: Windows - Setup C++
        if: runner.os == 'Windows'
        uses: aminya/setup-cpp@v1
        with:
          compiler: msvc
          vcvarsall: true
          cmake: true
          ninja: true
          vcpkg: false
          ccache: false
          conan: 2.0.17
          clangtidy: false
          task: false
          cppcheck: false
          gcovr: false
          opencppcoverage: false
      - name: Install compiler and Python
        run: pixi add cxx-compiler python
      - name: Build
        run: pixi run build_test
      - name: Run tests
        run: pixi run test
