name: Windows CI

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
         - compiler: msvc
           cc: "cl"
           cxx: "cl"
         - compiler: gcc
           cc: "gcc"
           cxx: "g++"
         - compiler: gcc
           cc: "clang"
           cxx: "clang++"
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: solver/test/environment.yml
          environment-name: ponio-solver-test
      - name: Configure
        shell: cmd /C CALL {0}
        run: |
          call micromamba activate ponio-solver-test
          cd solver
          make install
          cd test
          make test