name: Windows CI

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
         - compiler: msvc
           cc: "cl"
           cxx: "cl"
         - compiler: gcc
           cc: "gcc"
           cxx: "g++"
         - compiler: gcc
           cc: "clang"
           cxx: "clang++"
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: solver/test/environment.yml
          environment-name: ponio-solver-test
      - name: Conda informations
        shell: bash -l {0}
        run: |
          mamba info
          mamba list
      - name: Configure
        shell: bash -l {0}
        run: |
          export LDFLAGS="${LDFLAGS} -L$CONDA_PREFIX/lib"
          cd solver
          make install
          cd test
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} make test